//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT2_NongVanBach_2210900003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int ma_quan_tri { get; set; }
        public string ho_ten { get; set; }
        public string email { get; set; }
        public string mat_khau { get; set; }
    }
}
