//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT2_NongVanBach_2210900003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int ma_dat_ve { get; set; }
        public Nullable<int> ma_nguoi_dung { get; set; }
        public Nullable<int> ma_suat_chieu { get; set; }
        public string ghe_ngoi { get; set; }
        public Nullable<decimal> tong_tien { get; set; }
        public string trang_thai { get; set; }
        public Nullable<System.DateTime> ngay_dat { get; set; }
    
        public virtual User User { get; set; }
        public virtual Showtime Showtime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
