//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT2_NongVanBach_2210900003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DON_HANG
    {
        public int ID { get; set; }
        public int ID_DH { get; set; }
        public int ID_SP { get; set; }
        public int So_Luong { get; set; }
        public decimal Don_Gia { get; set; }
        public Nullable<decimal> Thanh_Tien { get; set; }
    
        public virtual DON_HANG DON_HANG { get; set; }
    }
}
