//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT2_NongVanBach_2210900003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movy()
        {
            this.Showtimes = new HashSet<Showtime>();
        }
    
        public int ma_phim { get; set; }
        public string ten_phim { get; set; }
        public string the_loai { get; set; }
        public string dao_dien { get; set; }
        public string dien_vien { get; set; }
        public Nullable<int> thoi_luong { get; set; }
        public Nullable<System.DateTime> ngay_phat_hanh { get; set; }
        public string mo_ta { get; set; }
        public string image_path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
       
        public virtual ICollection<Showtime> Showtimes { get; set; }
    }
}
