//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT2_NongVanBach_2210900003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Showtime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Showtime()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int ma_suat_chieu { get; set; }
        public Nullable<int> ma_phim { get; set; }
        public Nullable<int> ma_rap { get; set; }
        public Nullable<System.DateTime> ngay_chieu { get; set; }
        public Nullable<System.TimeSpan> gio_chieu { get; set; }
        public string phong_chieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Cinema Cinema { get; set; }
        public virtual Movy Movy { get; set; }
    }
}
