//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22_CNT2_NongVanBach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DON_HANG
    {
        public int ID { get; set; }
        public Nullable<int> ID_DH { get; set; }
        public Nullable<int> ID_SP { get; set; }
        public Nullable<int> So_Luong { get; set; }
        public Nullable<double> Don_gia { get; set; }
        public Nullable<double> Thanh_tien { get; set; }
    }
}
