//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22_CNT2_NongVanBach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Quanity { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
